@api = http://localhost:3001/products

GET {{api}}

### CREATE NEW COOLER

POST {{api}}
Content-Type: application/json

{
    "IdCooler": 777,
    "ModeloCooler": "PepsiRefri555",
    "Marca": "Pepsi",
    "Identificador": "CrioTec-5555G",
    "NumPuertas": 5,
    "SizeCliente": "Grande",
    "TypeDoor": "PepsiCola",
    "PotencialVentaMensual": "255 CU promedio",
    "CapacidadBottle": "945",
    "LlenadoPuerta": 6,
    "IngresoMensualCliente": 102060,
    "GananciaMensualCliente": 28350,
    "ConsumoEnergeticoMensual": "6.82 Kw/h",
    "ConsumoEnergeticoDinero": 4899

}

### GET COOLER BY ID

GET {{api}}/777

### DELETE COOLER BY ID

DELETE {{api}}/777

### TOTAL NUM OF COOLERS

GET {{api}}/count

### UPDATE COOLER

PUT {{api}}/777
Content-Type: application/json

{
    "ModeloCooler": "UPDATE",
    "Marca": "UPDATE",
    "Identificador": "UPDATE",
    "NumPuertas": 5,
    "SizeCliente": "Grande",
    "TypeDoor": "UPDATE",
    "PotencialVentaMensual": "UPDATE",
    "CapacidadBottle": 997,
    "LlenadoPuerta": 6,
    "IngresoMensualCliente": 102060,
    "GananciaMensualCliente": 28350,
    "ConsumoEnergeticoMensual": "99.99 Kw/h",
    "ConsumoEnergeticoDinero": 4899
}

### get totalOrders

GET http://localhost:3001/productos/totalordenes
Content-Content-Type: application/json


### get totalOrdersCancel

GET http://localhost:3001/productos/ordenescancel
Content-Type: application/json

### get totalOrdersAccepted

GET http://localhost:3001/productos/ordenesaceptadas
Content-Type: application/json


### get BestSelling

GET http://localhost:3001/kpi/bestselling
Content-Type: application/json

### get NewParteners

GET http://localhost:3001/kpi/newpartners
Content-Type: application/json

### get TotalPartners

GET http://localhost:3001/kpi/totalpartners
Content-Type: application/json

### get TotalCoolerOnLocation

GET http://localhost:3001/kpi/totalcoolersonlocation
Content-Type: application/json

### get TotalSolicitudMes

GET http://localhost:3001/kpi/solicitudesmes
Content-Type: application/json

### get BestSeller

GET http://localhost:3001/kpi/bestseller
Content-Type: application/json

### login

POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "davidgarza@arcacontal.com",
  "password": "6283849827"
}

### UPDATE Solicitud BY ID

PUT http://localhost:3001/productos/UpdateSolicitudById/4011/Pendiente
Content-Type: application/json

